// CASTED — curated Alter Ego character pool.
// Each entry is hand-picked and trait-tagged so the casting engine can match a
// viewer to someone who genuinely fits, draw from a deep + diverse field, and
// never repeat until the pool is exhausted. `reel` is a curated set of films
// that embody the character's energy — what you watch to "become" them tonight.

export type Tier = 'icon' | 'deep'

export interface PoolCharacter {
  id: string
  name: string
  actor: string
  film: string
  year: number
  tier: Tier
  /** One-line essence shown to the matching model and used in fallback copy. */
  essence: string
  /** Controlled-vocabulary trait tags used for deterministic fallback matching. */
  tags: string[]
  /** 3–4 short words shown on the reveal + share card. */
  vibe: string[]
  /** 6 curated films that embody this character's energy. */
  reel: string[]
}

export const CHARACTER_POOL: PoolCharacter[] = [
  // ── Cool / still / solitary ────────────────────────────────────────────────
  {
    id: 'jef-costello',
    name: 'Jef Costello',
    actor: 'Alain Delon',
    film: 'Le Samouraï',
    year: 1967,
    tier: 'deep',
    essence: 'A contract killer of monastic stillness — silence is his weapon, ritual his armor.',
    tags: ['solitary', 'still', 'controlled', 'cool', 'principled', 'melancholy'],
    vibe: ['Cold', 'Precise', 'Lonely', 'Iconic'],
    reel: ['Le Samouraï', 'Drive', 'The American', 'Ghost Dog: The Way of the Samurai', 'Collateral', 'Branded to Kill'],
  },
  {
    id: 'driver',
    name: 'The Driver',
    actor: 'Ryan Gosling',
    film: 'Drive',
    year: 2011,
    tier: 'icon',
    essence: 'A getaway driver who says little and feels everything beneath the calm.',
    tags: ['solitary', 'still', 'controlled', 'cool', 'romantic', 'wounded'],
    vibe: ['Quiet', 'Loyal', 'Dangerous', 'Neon'],
    reel: ['Drive', 'Le Samouraï', 'The Place Beyond the Pines', 'Baby Driver', 'Only God Forgives', 'Thief'],
  },
  {
    id: 'john-wick',
    name: 'John Wick',
    actor: 'Keanu Reeves',
    film: 'John Wick',
    year: 2014,
    tier: 'icon',
    essence: 'Grief turned into pure, lethal focus — calm right up until he isn’t.',
    tags: ['solitary', 'controlled', 'vengeful', 'fearless', 'wounded', 'kinetic'],
    vibe: ['Lethal', 'Calm', 'Relentless', 'Grieving'],
    reel: ['John Wick', 'The Equalizer', 'Nobody', 'Léon: The Professional', 'Atomic Blonde', 'Sicario'],
  },
  {
    id: 'man-with-no-name',
    name: 'The Man With No Name',
    actor: 'Clint Eastwood',
    film: 'The Good, the Bad and the Ugly',
    year: 1966,
    tier: 'icon',
    essence: 'A drifter with his own code, unreadable behind the cigarillo and squint.',
    tags: ['solitary', 'cool', 'controlled', 'principled', 'outsider', 'still'],
    vibe: ['Stoic', 'Sharp', 'Unbothered', 'Mythic'],
    reel: ['The Good, the Bad and the Ugly', 'Once Upon a Time in the West', 'Yojimbo', 'Unforgiven', 'High Plains Drifter', 'The Proposition'],
  },
  {
    id: 'leon',
    name: 'Léon',
    actor: 'Jean Reno',
    film: 'Léon: The Professional',
    year: 1994,
    tier: 'icon',
    essence: 'A lonely hitman whose buried tenderness becomes his undoing and his grace.',
    tags: ['solitary', 'loyal', 'tender', 'controlled', 'wounded', 'protector'],
    vibe: ['Lonely', 'Loyal', 'Gentle', 'Lethal'],
    reel: ['Léon: The Professional', 'Gloria', 'The Professional', 'Logan', 'A Bittersweet Life', 'Drive'],
  },
  {
    id: 'ghost-dog',
    name: 'Ghost Dog',
    actor: 'Forest Whitaker',
    film: 'Ghost Dog: The Way of the Samurai',
    year: 1999,
    tier: 'deep',
    essence: 'A hitman who lives by the samurai code in a world that forgot honor.',
    tags: ['solitary', 'principled', 'still', 'loyal', 'outsider', 'melancholy'],
    vibe: ['Honorable', 'Solitary', 'Soulful', 'Anachronistic'],
    reel: ['Ghost Dog: The Way of the Samurai', 'Le Samouraï', 'Dead Man', 'Blue Ruin', 'The Limits of Control', 'Paterson'],
  },

  // ── Chaos / wild / rebellious ──────────────────────────────────────────────
  {
    id: 'tyler-durden',
    name: 'Tyler Durden',
    actor: 'Brad Pitt',
    film: 'Fight Club',
    year: 1999,
    tier: 'icon',
    essence: 'Charisma weaponized — the voice telling you to burn the comfortable life down.',
    tags: ['chaotic', 'magnetic', 'rebellious', 'fearless', 'dark', 'kinetic'],
    vibe: ['Chaotic', 'Magnetic', 'Anarchic', 'Free'],
    reel: ['Fight Club', 'American Psycho', 'Trainspotting', 'A Clockwork Orange', 'Natural Born Killers', 'Snatch'],
  },
  {
    id: 'jack-sparrow',
    name: 'Captain Jack Sparrow',
    actor: 'Johnny Depp',
    film: 'Pirates of the Caribbean: The Curse of the Black Pearl',
    year: 2003,
    tier: 'icon',
    essence: 'Survival as performance art — always three moves and one rum ahead.',
    tags: ['chaotic', 'free', 'magnetic', 'whimsical', 'survivor', 'outsider'],
    vibe: ['Roguish', 'Cunning', 'Free', 'Theatrical'],
    reel: ['Pirates of the Caribbean: The Curse of the Black Pearl', 'The Princess Bride', 'Indiana Jones and the Raiders of the Lost Ark', 'The Mask of Zorro', 'Treasure Planet', 'Master and Commander'],
  },
  {
    id: 'mia-wallace',
    name: 'Mia Wallace',
    actor: 'Uma Thurman',
    film: 'Pulp Fiction',
    year: 1994,
    tier: 'icon',
    essence: 'Magnetic and unpredictable, she turns an ordinary night into mythology.',
    tags: ['magnetic', 'free', 'chaotic', 'cool', 'emotional', 'wounded'],
    vibe: ['Magnetic', 'Cool', 'Mysterious', 'Night Energy'],
    reel: ['Pulp Fiction', 'Jackie Brown', 'Lost in Translation', 'Belle de Jour', 'Mulholland Drive', 'Gia'],
  },
  {
    id: 'randle-mcmurphy',
    name: 'Randle P. McMurphy',
    actor: 'Jack Nicholson',
    film: 'One Flew Over the Cuckoo’s Nest',
    year: 1975,
    tier: 'icon',
    essence: 'A live wire who refuses to be tamed, and pays for waking everyone up.',
    tags: ['rebellious', 'magnetic', 'chaotic', 'fearless', 'free', 'wounded'],
    vibe: ['Rebellious', 'Alive', 'Defiant', 'Magnetic'],
    reel: ['One Flew Over the Cuckoo’s Nest', 'Cool Hand Luke', 'Easy Rider', 'The Fisher King', 'Birdy', 'Midnight Cowboy'],
  },
  {
    id: 'harley-quinn',
    name: 'Harley Quinn',
    actor: 'Margot Robbie',
    film: 'Birds of Prey',
    year: 2020,
    tier: 'icon',
    essence: 'Chaos with glitter — heartbreak rebuilt into fearless, technicolor mayhem.',
    tags: ['chaotic', 'free', 'emotional', 'rebellious', 'magnetic', 'survivor'],
    vibe: ['Chaotic', 'Fearless', 'Playful', 'Wild'],
    reel: ['Birds of Prey', 'Thelma & Louise', 'Spring Breakers', 'Jennifer’s Body', 'Tank Girl', 'Promising Young Woman'],
  },

  // ── Intellect / genius / outsider ──────────────────────────────────────────
  {
    id: 'lisbeth-salander',
    name: 'Lisbeth Salander',
    actor: 'Noomi Rapace',
    film: 'The Girl with the Dragon Tattoo',
    year: 2009,
    tier: 'icon',
    essence: 'A brilliant outsider who trusts no one and forgets nothing.',
    tags: ['cerebral', 'solitary', 'vengeful', 'outsider', 'survivor', 'dark'],
    vibe: ['Genius', 'Outsider', 'Fierce', 'Guarded'],
    reel: ['The Girl with the Dragon Tattoo', 'Hackers', 'Run Lola Run', 'Gone Girl', 'Hanna', 'Millennium'],
  },
  {
    id: 'will-hunting',
    name: 'Will Hunting',
    actor: 'Matt Damon',
    film: 'Good Will Hunting',
    year: 1997,
    tier: 'icon',
    essence: 'A genius hiding behind a wall, terrified that being seen means being left.',
    tags: ['cerebral', 'wounded', 'guarded', 'outsider', 'emotional', 'loyal'],
    vibe: ['Gifted', 'Guarded', 'Searching', 'Loyal'],
    reel: ['Good Will Hunting', 'Dead Poets Society', 'A Beautiful Mind', 'The Spectacular Now', 'Manchester by the Sea', 'Garden State'],
  },
  {
    id: 'amelie',
    name: 'Amélie Poulain',
    actor: 'Audrey Tautou',
    film: 'Amélie',
    year: 2001,
    tier: 'icon',
    essence: 'A shy dreamer who engineers small miracles for everyone but herself.',
    tags: ['whimsical', 'dreamer', 'tender', 'solitary', 'romantic', 'light'],
    vibe: ['Whimsical', 'Romantic', 'Curious', 'Tender'],
    reel: ['Amélie', 'Lost in Translation', 'The Science of Sleep', 'Paterson', 'Punch-Drunk Love', 'Her'],
  },

  // ── Warriors / fearless / protectors ───────────────────────────────────────
  {
    id: 'ellen-ripley',
    name: 'Ellen Ripley',
    actor: 'Sigourney Weaver',
    film: 'Aliens',
    year: 1986,
    tier: 'icon',
    essence: 'Survival incarnate — she stays clear-eyed when everyone else is screaming.',
    tags: ['fearless', 'protector', 'controlled', 'survivor', 'leader', 'principled'],
    vibe: ['Fearless', 'Steady', 'Protective', 'Iron'],
    reel: ['Aliens', 'Alien', 'Terminator 2: Judgment Day', 'Gravity', 'Annihilation', 'Prey'],
  },
  {
    id: 'furiosa',
    name: 'Imperator Furiosa',
    actor: 'Charlize Theron',
    film: 'Mad Max: Fury Road',
    year: 2015,
    tier: 'icon',
    essence: 'A warrior driving toward redemption through fire, fury, and unbreakable will.',
    tags: ['fearless', 'vengeful', 'protector', 'survivor', 'leader', 'wounded'],
    vibe: ['Fierce', 'Driven', 'Redemptive', 'Iron'],
    reel: ['Mad Max: Fury Road', 'Furiosa: A Mad Max Saga', 'Atomic Blonde', 'Hanna', 'The Old Guard', 'Aliens'],
  },
  {
    id: 'beatrix-kiddo',
    name: 'The Bride',
    actor: 'Uma Thurman',
    film: 'Kill Bill: Vol. 1',
    year: 2003,
    tier: 'icon',
    essence: 'Vengeance with a death list and the discipline to finish it.',
    tags: ['vengeful', 'fearless', 'controlled', 'kinetic', 'survivor', 'principled'],
    vibe: ['Vengeful', 'Focused', 'Lethal', 'Unstoppable'],
    reel: ['Kill Bill: Vol. 1', 'Kill Bill: Vol. 2', 'Lady Snowblood', 'Oldboy', 'Hanna', 'Promising Young Woman'],
  },
  {
    id: 'maximus',
    name: 'Maximus',
    actor: 'Russell Crowe',
    film: 'Gladiator',
    year: 2000,
    tier: 'icon',
    essence: 'A soldier stripped of everything who fights for honor and the dead he loved.',
    tags: ['principled', 'fearless', 'loyal', 'vengeful', 'leader', 'wounded'],
    vibe: ['Honorable', 'Resolute', 'Grieving', 'Mighty'],
    reel: ['Gladiator', 'Braveheart', 'The Last Samurai', '300', 'Kingdom of Heaven', 'Spartacus'],
  },
  {
    id: 'mulan',
    name: 'Mulan',
    actor: 'Ming-Na Wen',
    film: 'Mulan',
    year: 1998,
    tier: 'icon',
    essence: 'She breaks every rule to protect her family and finds out who she really is.',
    tags: ['protector', 'fearless', 'loyal', 'rebellious', 'dutiful', 'seeker'],
    vibe: ['Brave', 'Loyal', 'Determined', 'True'],
    reel: ['Mulan', 'Moana', 'Brave', 'Princess Mononoke', 'Whale Rider', 'The Eagle Huntress'],
  },
  {
    id: 'sarah-connor',
    name: 'Sarah Connor',
    actor: 'Linda Hamilton',
    film: 'Terminator 2: Judgment Day',
    year: 1991,
    tier: 'icon',
    essence: 'A mother forged into a soldier by a future only she can see coming.',
    tags: ['protector', 'fearless', 'survivor', 'controlled', 'vengeful', 'leader'],
    vibe: ['Hardened', 'Protective', 'Relentless', 'Prophetic'],
    reel: ['Terminator 2: Judgment Day', 'The Terminator', 'Aliens', 'Children of Men', 'A Quiet Place', 'Prey'],
  },
  {
    id: 'okoye',
    name: 'Okoye',
    actor: 'Danai Gurira',
    film: 'Black Panther',
    year: 2018,
    tier: 'deep',
    essence: 'Duty and love at war inside a warrior who would die for her nation.',
    tags: ['dutiful', 'fearless', 'loyal', 'principled', 'protector', 'leader'],
    vibe: ['Disciplined', 'Loyal', 'Regal', 'Fierce'],
    reel: ['Black Panther', 'Wonder Woman', 'The Woman King', 'Mad Max: Fury Road', 'Gladiator', 'Mulan'],
  },

  // ── Ambition / hunger / drive ──────────────────────────────────────────────
  {
    id: 'daniel-plainview',
    name: 'Daniel Plainview',
    actor: 'Daniel Day-Lewis',
    film: 'There Will Be Blood',
    year: 2007,
    tier: 'icon',
    essence: 'Ambition with no floor — a man who wins everything and loses his soul.',
    tags: ['ambitious', 'ruthless', 'solitary', 'dark', 'controlled', 'wounded'],
    vibe: ['Ruthless', 'Driven', 'Cold', 'Towering'],
    reel: ['There Will Be Blood', 'The Master', 'Citizen Kane', 'No Country for Old Men', 'The Treasure of the Sierra Madre', 'Phantom Thread'],
  },
  {
    id: 'andrew-neiman',
    name: 'Andrew Neiman',
    actor: 'Miles Teller',
    film: 'Whiplash',
    year: 2014,
    tier: 'icon',
    essence: 'Obsession with greatness that burns away everything else in his life.',
    tags: ['ambitious', 'wounded', 'solitary', 'kinetic', 'seeker', 'emotional'],
    vibe: ['Obsessive', 'Driven', 'Relentless', 'Burning'],
    reel: ['Whiplash', 'Black Swan', 'The Wrestler', 'Raging Bull', 'Sound of Metal', 'Tár'],
  },
  {
    id: 'nina-sayers',
    name: 'Nina Sayers',
    actor: 'Natalie Portman',
    film: 'Black Swan',
    year: 2010,
    tier: 'icon',
    essence: 'Perfectionism that consumes her until she can’t tell discipline from madness.',
    tags: ['ambitious', 'fearful', 'emotional', 'wounded', 'solitary', 'seeker'],
    vibe: ['Driven', 'Fragile', 'Transforming', 'Intense'],
    reel: ['Black Swan', 'Whiplash', 'The Red Shoes', 'Perfect Blue', 'Tár', 'Repulsion'],
  },
  {
    id: 'miranda-priestly',
    name: 'Miranda Priestly',
    actor: 'Meryl Streep',
    film: 'The Devil Wears Prada',
    year: 2006,
    tier: 'icon',
    essence: 'Power so total it never needs to raise its voice.',
    tags: ['ambitious', 'controlled', 'ruthless', 'leader', 'principled', 'cool'],
    vibe: ['Commanding', 'Exacting', 'Untouchable', 'Sharp'],
    reel: ['The Devil Wears Prada', 'Phantom Thread', 'Tár', 'The Queen', 'Working Girl', 'Michael Clayton'],
  },
  {
    id: 'jordan-belfort',
    name: 'Jordan Belfort',
    actor: 'Leonardo DiCaprio',
    film: 'The Wolf of Wall Street',
    year: 2013,
    tier: 'icon',
    essence: 'Appetite as a personality — more, faster, louder, until the crash.',
    tags: ['ambitious', 'magnetic', 'chaotic', 'ruthless', 'free', 'dark'],
    vibe: ['Excess', 'Magnetic', 'Reckless', 'Hungry'],
    reel: ['The Wolf of Wall Street', 'Goodfellas', 'Scarface', 'American Hustle', 'Casino', 'Boiler Room'],
  },

  // ── Menace / villains / monsters ───────────────────────────────────────────
  {
    id: 'hannibal-lecter',
    name: 'Hannibal Lecter',
    actor: 'Anthony Hopkins',
    film: 'The Silence of the Lambs',
    year: 1991,
    tier: 'icon',
    essence: 'Terrifying intellect and impeccable manners wrapped around something monstrous.',
    tags: ['cerebral', 'menacing', 'controlled', 'dark', 'magnetic', 'solitary'],
    vibe: ['Brilliant', 'Menacing', 'Refined', 'Predatory'],
    reel: ['The Silence of the Lambs', 'Se7en', 'Zodiac', 'Prisoners', 'Red Dragon', 'The Talented Mr. Ripley'],
  },
  {
    id: 'anton-chigurh',
    name: 'Anton Chigurh',
    actor: 'Javier Bardem',
    film: 'No Country for Old Men',
    year: 2007,
    tier: 'icon',
    essence: 'Fate in human form — implacable, principled in his own terrifying way.',
    tags: ['menacing', 'controlled', 'dark', 'solitary', 'principled', 'still'],
    vibe: ['Implacable', 'Cold', 'Fateful', 'Terrifying'],
    reel: ['No Country for Old Men', 'Sicario', 'There Will Be Blood', 'The Counselor', 'Wind River', 'Blood Simple'],
  },
  {
    id: 'patrick-bateman',
    name: 'Patrick Bateman',
    actor: 'Christian Bale',
    film: 'American Psycho',
    year: 2000,
    tier: 'icon',
    essence: 'A polished mask over a void, performing humanity he doesn’t feel.',
    tags: ['menacing', 'controlled', 'dark', 'ambitious', 'solitary', 'cerebral'],
    vibe: ['Polished', 'Empty', 'Dangerous', 'Vain'],
    reel: ['American Psycho', 'Nightcrawler', 'Fight Club', 'The Talented Mr. Ripley', 'Gone Girl', 'Maniac'],
  },
  {
    id: 'amy-dunne',
    name: 'Amy Dunne',
    actor: 'Rosamund Pike',
    film: 'Gone Girl',
    year: 2014,
    tier: 'icon',
    essence: 'A mastermind who turns being underestimated into a weapon of total control.',
    tags: ['cerebral', 'menacing', 'controlled', 'vengeful', 'dark', 'ambitious'],
    vibe: ['Calculating', 'Cold', 'Brilliant', 'Vengeful'],
    reel: ['Gone Girl', 'The Girl with the Dragon Tattoo', 'Basic Instinct', 'Promising Young Woman', 'Nightcrawler', 'Notes on a Scandal'],
  },
  {
    id: 'the-joker',
    name: 'The Joker',
    actor: 'Heath Ledger',
    film: 'The Dark Knight',
    year: 2008,
    tier: 'icon',
    essence: 'An agent of chaos who just wants to watch the world reveal itself.',
    tags: ['chaotic', 'dark', 'cerebral', 'menacing', 'rebellious', 'magnetic'],
    vibe: ['Anarchic', 'Brilliant', 'Unhinged', 'Magnetic'],
    reel: ['The Dark Knight', 'Joker', 'A Clockwork Orange', 'No Country for Old Men', 'Funny Games', 'V for Vendetta'],
  },
  {
    id: 'nurse-ratched',
    name: 'Nurse Ratched',
    actor: 'Louise Fletcher',
    film: 'One Flew Over the Cuckoo’s Nest',
    year: 1975,
    tier: 'deep',
    essence: 'Control disguised as care — tyranny in a calm, reasonable voice.',
    tags: ['controlled', 'menacing', 'ruthless', 'dark', 'principled', 'still'],
    vibe: ['Controlling', 'Cold', 'Composed', 'Suffocating'],
    reel: ['One Flew Over the Cuckoo’s Nest', 'Whiplash', 'The Devil Wears Prada', 'Misery', 'Gone Girl', 'Notes on a Scandal'],
  },

  // ── Romantics / dreamers ───────────────────────────────────────────────────
  {
    id: 'jay-gatsby',
    name: 'Jay Gatsby',
    actor: 'Leonardo DiCaprio',
    film: 'The Great Gatsby',
    year: 2013,
    tier: 'icon',
    essence: 'A self-made dreamer in love with a version of the past he can’t buy back.',
    tags: ['romantic', 'dreamer', 'ambitious', 'wounded', 'magnetic', 'melancholy'],
    vibe: ['Romantic', 'Yearning', 'Lavish', 'Doomed'],
    reel: ['The Great Gatsby', 'Atonement', 'In the Mood for Love', 'The Age of Innocence', 'Moulin Rouge!', 'Brideshead Revisited'],
  },
  {
    id: 'clementine',
    name: 'Clementine Kruczynski',
    actor: 'Kate Winslet',
    film: 'Eternal Sunshine of the Spotless Mind',
    year: 2004,
    tier: 'icon',
    essence: 'A free spirit who feels in technicolor and refuses to be anyone’s idea.',
    tags: ['free', 'emotional', 'romantic', 'whimsical', 'wounded', 'magnetic'],
    vibe: ['Free', 'Impulsive', 'Vivid', 'Searching'],
    reel: ['Eternal Sunshine of the Spotless Mind', 'Her', 'Blue Valentine', '500 Days of Summer', 'Ruby Sparks', 'Lost in Translation'],
  },
  {
    id: 'theodore-twombly',
    name: 'Theodore Twombly',
    actor: 'Joaquin Phoenix',
    film: 'Her',
    year: 2013,
    tier: 'deep',
    essence: 'A gentle, lonely romantic learning that love means letting it change you.',
    tags: ['romantic', 'tender', 'solitary', 'emotional', 'melancholy', 'dreamer'],
    vibe: ['Gentle', 'Lonely', 'Tender', 'Open'],
    reel: ['Her', 'Lost in Translation', 'Eternal Sunshine of the Spotless Mind', 'Past Lives', 'Paterson', 'Columbus'],
  },
  {
    id: 'holly-golightly',
    name: 'Holly Golightly',
    actor: 'Audrey Hepburn',
    film: 'Breakfast at Tiffany’s',
    year: 1961,
    tier: 'icon',
    essence: 'Effervescent and untethered, outrunning a sadness she won’t name.',
    tags: ['free', 'magnetic', 'whimsical', 'wounded', 'romantic', 'solitary'],
    vibe: ['Charming', 'Free', 'Glamorous', 'Restless'],
    reel: ['Breakfast at Tiffany’s', 'Funny Face', 'La La Land', 'Frances Ha', 'Roman Holiday', 'Annie Hall'],
  },
  {
    id: 'chow-mo-wan',
    name: 'Chow Mo-wan',
    actor: 'Tony Leung',
    film: 'In the Mood for Love',
    year: 2000,
    tier: 'deep',
    essence: 'Aching restraint — a love held so carefully it’s never allowed to happen.',
    tags: ['romantic', 'melancholy', 'controlled', 'tender', 'solitary', 'principled'],
    vibe: ['Yearning', 'Restrained', 'Elegant', 'Heartbroken'],
    reel: ['In the Mood for Love', 'Chungking Express', 'Past Lives', 'Lost in Translation', 'Happy Together', 'Norwegian Wood'],
  },

  // ── Lonely intensity / wounded seekers ─────────────────────────────────────
  {
    id: 'travis-bickle',
    name: 'Travis Bickle',
    actor: 'Robert De Niro',
    film: 'Taxi Driver',
    year: 1976,
    tier: 'icon',
    essence: 'Aching isolation curdling into a dangerous need to matter.',
    tags: ['solitary', 'wounded', 'dark', 'seeker', 'melancholy', 'rebellious'],
    vibe: ['Lonely', 'Intense', 'Restless', 'Combustible'],
    reel: ['Taxi Driver', 'Joker', 'You Were Never Really Here', 'First Reformed', 'Nightcrawler', 'The King of Comedy'],
  },
  {
    id: 'llewyn-davis',
    name: 'Llewyn Davis',
    actor: 'Oscar Isaac',
    film: 'Inside Llewyn Davis',
    year: 2013,
    tier: 'deep',
    essence: 'A gifted, self-sabotaging artist going in circles he can’t see.',
    tags: ['solitary', 'wounded', 'melancholy', 'seeker', 'principled', 'emotional'],
    vibe: ['Melancholy', 'Gifted', 'Stuck', 'Soulful'],
    reel: ['Inside Llewyn Davis', 'A Star Is Born', 'Frances Ha', 'Paterson', 'Her', 'The Wrestler'],
  },
  {
    id: 'arthur-fleck',
    name: 'Arthur Fleck',
    actor: 'Joaquin Phoenix',
    film: 'Joker',
    year: 2019,
    tier: 'icon',
    essence: 'A man invisible to the world until the world makes him impossible to ignore.',
    tags: ['wounded', 'solitary', 'dark', 'emotional', 'outsider', 'rebellious'],
    vibe: ['Broken', 'Yearning', 'Volatile', 'Tragic'],
    reel: ['Joker', 'Taxi Driver', 'The King of Comedy', 'You Were Never Really Here', 'One Hour Photo', 'Falling Down'],
  },

  // ── Survivors / grit / heart ───────────────────────────────────────────────
  {
    id: 'mattie-ross',
    name: 'Mattie Ross',
    actor: 'Hailee Steinfeld',
    film: 'True Grit',
    year: 2010,
    tier: 'deep',
    essence: 'A fearless girl with an old soul who will not be talked out of justice.',
    tags: ['fearless', 'principled', 'seeker', 'controlled', 'vengeful', 'leader'],
    vibe: ['Steely', 'Sharp', 'Determined', 'Unflinching'],
    reel: ['True Grit', 'Winter’s Bone', 'The Night of the Hunter', 'Leave No Trace', 'Hell or High Water', 'News of the World'],
  },
  {
    id: 'chiron',
    name: 'Chiron',
    actor: 'Trevante Rhodes',
    film: 'Moonlight',
    year: 2016,
    tier: 'deep',
    essence: 'A tender soul who armors himself to survive, aching to be known.',
    tags: ['wounded', 'tender', 'solitary', 'seeker', 'emotional', 'survivor'],
    vibe: ['Tender', 'Guarded', 'Yearning', 'Quiet'],
    reel: ['Moonlight', 'Past Lives', 'Beautiful Boy', 'The Florida Project', 'Aftersun', 'Call Me by Your Name'],
  },
  {
    id: 'ree-dolly',
    name: 'Ree Dolly',
    actor: 'Jennifer Lawrence',
    film: 'Winter’s Bone',
    year: 2010,
    tier: 'deep',
    essence: 'Unbending resolve holding a family together against a stacked world.',
    tags: ['protector', 'survivor', 'fearless', 'dutiful', 'principled', 'loyal'],
    vibe: ['Tough', 'Loyal', 'Resilient', 'Grounded'],
    reel: ['Winter’s Bone', 'True Grit', 'Leave No Trace', 'Frozen River', 'Hell or High Water', 'Nomadland'],
  },
  {
    id: 'hushpuppy',
    name: 'Hushpuppy',
    actor: 'Quvenzhané Wallis',
    film: 'Beasts of the Southern Wild',
    year: 2012,
    tier: 'deep',
    essence: 'A tiny, mythic force of nature who refuses to be small.',
    tags: ['fearless', 'free', 'survivor', 'dreamer', 'wild', 'principled'],
    vibe: ['Wild', 'Brave', 'Untamed', 'Luminous'],
    reel: ['Beasts of the Southern Wild', 'The Florida Project', 'Where the Wild Things Are', 'Pan’s Labyrinth', 'Whale Rider', 'Leave No Trace'],
  },

  // ── World cinema deep cuts ─────────────────────────────────────────────────
  {
    id: 'oh-dae-su',
    name: 'Oh Dae-su',
    actor: 'Choi Min-sik',
    film: 'Oldboy',
    year: 2003,
    tier: 'deep',
    essence: 'A man remade by vengeance, devouring the mystery of his own ruin.',
    tags: ['vengeful', 'wounded', 'kinetic', 'survivor', 'dark', 'seeker'],
    vibe: ['Vengeful', 'Feral', 'Haunted', 'Relentless'],
    reel: ['Oldboy', 'I Saw the Devil', 'The Chaser', 'A Bittersweet Life', 'Memories of Murder', 'Lady Vengeance'],
  },
  {
    id: 'kikuchiyo',
    name: 'Kikuchiyo',
    actor: 'Toshiro Mifune',
    film: 'Seven Samurai',
    year: 1954,
    tier: 'deep',
    essence: 'A wild, big-hearted fraud who becomes the bravest of them all.',
    tags: ['chaotic', 'fearless', 'loyal', 'wounded', 'free', 'protector'],
    vibe: ['Wild', 'Brave', 'Big-Hearted', 'Untamed'],
    reel: ['Seven Samurai', 'Yojimbo', 'Sanjuro', 'Harakiri', '13 Assassins', 'The Hidden Fortress'],
  },
  {
    id: 'ki-taek',
    name: 'Ki-taek',
    actor: 'Song Kang-ho',
    film: 'Parasite',
    year: 2019,
    tier: 'deep',
    essence: 'A father improvising dignity in a world with no plan for him.',
    tags: ['survivor', 'loyal', 'wounded', 'emotional', 'outsider', 'principled'],
    vibe: ['Resourceful', 'Weary', 'Loving', 'Cornered'],
    reel: ['Parasite', 'Shoplifters', 'Burning', 'The Florida Project', 'A Separation', 'Roma'],
  },
  {
    id: 'su-li-zhen',
    name: 'Su Li-zhen',
    actor: 'Maggie Cheung',
    film: 'In the Mood for Love',
    year: 2000,
    tier: 'deep',
    essence: 'Grace under longing — a woman holding her composure like a vow.',
    tags: ['romantic', 'controlled', 'melancholy', 'tender', 'principled', 'solitary'],
    vibe: ['Elegant', 'Restrained', 'Yearning', 'Luminous'],
    reel: ['In the Mood for Love', 'Past Lives', 'Norwegian Wood', 'The Handmaiden', 'Lust, Caution', 'Happy Together'],
  },
  {
    id: 'cleo',
    name: 'Cleo',
    actor: 'Yalitza Aparicio',
    film: 'Roma',
    year: 2018,
    tier: 'deep',
    essence: 'Quiet, immense devotion holding a family up while carrying her own grief.',
    tags: ['tender', 'loyal', 'survivor', 'dutiful', 'emotional', 'protector'],
    vibe: ['Gentle', 'Devoted', 'Resilient', 'Quiet'],
    reel: ['Roma', 'Shoplifters', 'The Florida Project', 'Minari', 'A Separation', 'Parasite'],
  },

  // ── Animation ──────────────────────────────────────────────────────────────
  {
    id: 'chihiro',
    name: 'Chihiro',
    actor: 'Rumi Hiiragi',
    film: 'Spirited Away',
    year: 2001,
    tier: 'icon',
    essence: 'An ordinary kid who finds extraordinary courage when everything’s strange.',
    tags: ['seeker', 'tender', 'fearless', 'loyal', 'dreamer', 'survivor'],
    vibe: ['Brave', 'Curious', 'Kind', 'Resilient'],
    reel: ['Spirited Away', 'My Neighbor Totoro', 'Princess Mononoke', 'Coraline', 'Kiki’s Delivery Service', 'Wolfwalkers'],
  },
  {
    id: 'san-mononoke',
    name: 'San',
    actor: 'Yuriko Ishida',
    film: 'Princess Mononoke',
    year: 1997,
    tier: 'deep',
    essence: 'A fierce wild heart caught between the forest she loves and the humans she hates.',
    tags: ['wild', 'fearless', 'protector', 'rebellious', 'principled', 'outsider'],
    vibe: ['Fierce', 'Wild', 'Loyal', 'Untamed'],
    reel: ['Princess Mononoke', 'Nausicaä of the Valley of the Wind', 'Brave', 'Wolfwalkers', 'How to Train Your Dragon', 'The Tale of the Princess Kaguya'],
  },
  {
    id: 'carl-fredricksen',
    name: 'Carl Fredricksen',
    actor: 'Ed Asner',
    film: 'Up',
    year: 2009,
    tier: 'icon',
    essence: 'A grieving old romantic who learns the adventure was the love all along.',
    tags: ['loyal', 'wounded', 'tender', 'principled', 'melancholy', 'dreamer'],
    vibe: ['Grumpy', 'Loving', 'Loyal', 'Soulful'],
    reel: ['Up', 'WALL·E', 'About Schmidt', 'A Man Called Otto', 'The Straight Story', 'Coco'],
  },
  {
    id: 'wall-e',
    name: 'WALL·E',
    actor: 'Ben Burtt',
    film: 'WALL·E',
    year: 2008,
    tier: 'icon',
    essence: 'A lonely little romantic who keeps hope (and love) alive in the rubble.',
    tags: ['tender', 'solitary', 'dreamer', 'loyal', 'romantic', 'principled'],
    vibe: ['Gentle', 'Hopeful', 'Devoted', 'Curious'],
    reel: ['WALL·E', 'Up', 'The Iron Giant', 'E.T. the Extra-Terrestrial', 'Big Hero 6', 'Castle in the Sky'],
  },

  // ── Charm / effortless cool ────────────────────────────────────────────────
  {
    id: 'the-dude',
    name: 'The Dude',
    actor: 'Jeff Bridges',
    film: 'The Big Lebowski',
    year: 1998,
    tier: 'icon',
    essence: 'Effortless chill — abiding through chaos with a White Russian and zero ego.',
    tags: ['free', 'cool', 'whimsical', 'principled', 'social', 'still'],
    vibe: ['Easygoing', 'Chill', 'Unbothered', 'Zen'],
    reel: ['The Big Lebowski', 'Inherent Vice', 'Pineapple Express', 'Almost Famous', 'Harold and Maude', 'Withnail & I'],
  },
  {
    id: 'ferris-bueller',
    name: 'Ferris Bueller',
    actor: 'Matthew Broderick',
    film: 'Ferris Bueller’s Day Off',
    year: 1986,
    tier: 'icon',
    essence: 'A charming maestro of seizing the day and bending the world his way.',
    tags: ['free', 'magnetic', 'whimsical', 'social', 'rebellious', 'light'],
    vibe: ['Charming', 'Carefree', 'Clever', 'Alive'],
    reel: ['Ferris Bueller’s Day Off', 'The Breakfast Club', 'Booksmart', 'Risky Business', 'Adventureland', 'Dazed and Confused'],
  },
  {
    id: 'jules-winnfield',
    name: 'Jules Winnfield',
    actor: 'Samuel L. Jackson',
    film: 'Pulp Fiction',
    year: 1994,
    tier: 'icon',
    essence: 'Cool, philosophical menace — a man mid-transformation toward grace.',
    tags: ['cool', 'magnetic', 'principled', 'seeker', 'controlled', 'dark'],
    vibe: ['Cool', 'Philosophical', 'Commanding', 'Changing'],
    reel: ['Pulp Fiction', 'Jackie Brown', 'Goodfellas', 'Snatch', 'Reservoir Dogs', 'Coffy'],
  },
  {
    id: 'marge-gunderson',
    name: 'Marge Gunderson',
    actor: 'Frances McDormand',
    film: 'Fargo',
    year: 1996,
    tier: 'icon',
    essence: 'Decency and sharp wits underestimated by everyone — to their cost.',
    tags: ['principled', 'cerebral', 'controlled', 'loyal', 'leader', 'light'],
    vibe: ['Decent', 'Shrewd', 'Steady', 'Warm'],
    reel: ['Fargo', 'Three Billboards Outside Ebbing, Missouri', 'Wind River', 'Knives Out', 'Zodiac', 'Prisoners'],
  },

  // ── Seekers / detectives / dreamers of the truth ───────────────────────────
  {
    id: 'rick-deckard',
    name: 'Rick Deckard',
    actor: 'Harrison Ford',
    film: 'Blade Runner',
    year: 1982,
    tier: 'icon',
    essence: 'A weary hunter haunted by what it means to be real.',
    tags: ['solitary', 'seeker', 'melancholy', 'controlled', 'wounded', 'principled'],
    vibe: ['Weary', 'Searching', 'Noir', 'Haunted'],
    reel: ['Blade Runner', 'Blade Runner 2049', 'Ghost in the Shell', 'Minority Report', 'Dark City', 'Gattaca'],
  },
  {
    id: 'clarice-starling',
    name: 'Clarice Starling',
    actor: 'Jodie Foster',
    film: 'The Silence of the Lambs',
    year: 1991,
    tier: 'icon',
    essence: 'Quiet steel — she walks into the dark to silence her own ghosts.',
    tags: ['principled', 'fearless', 'seeker', 'controlled', 'wounded', 'cerebral'],
    vibe: ['Brave', 'Driven', 'Composed', 'Haunted'],
    reel: ['The Silence of the Lambs', 'Zodiac', 'Prisoners', 'Mare of Easttown', 'Wind River', 'The Girl with the Dragon Tattoo'],
  },
  {
    id: 'chihiro-pan',
    name: 'Ofelia',
    actor: 'Ivana Baquero',
    film: 'Pan’s Labyrinth',
    year: 2006,
    tier: 'deep',
    essence: 'A dreamer who chooses imagination and courage against a brutal world.',
    tags: ['dreamer', 'fearless', 'tender', 'principled', 'seeker', 'wounded'],
    vibe: ['Imaginative', 'Brave', 'Pure', 'Defiant'],
    reel: ['Pan’s Labyrinth', 'The Spirit of the Beehive', 'Beasts of the Southern Wild', 'A Monster Calls', 'Coraline', 'Tideland'],
  },

  // ── Free spirits / magnetic women ──────────────────────────────────────────
  {
    id: 'jackie-brown',
    name: 'Jackie Brown',
    actor: 'Pam Grier',
    film: 'Jackie Brown',
    year: 1997,
    tier: 'deep',
    essence: 'Grace under pressure — she outsmarts every man who underestimates her.',
    tags: ['cool', 'controlled', 'survivor', 'cerebral', 'principled', 'magnetic'],
    vibe: ['Cool', 'Smart', 'Composed', 'Unshakable'],
    reel: ['Jackie Brown', 'Foxy Brown', 'Out of Sight', 'Widows', 'Coffy', 'The Long Goodbye'],
  },
  {
    id: 'frances-ha',
    name: 'Frances',
    actor: 'Greta Gerwig',
    film: 'Frances Ha',
    year: 2012,
    tier: 'deep',
    essence: 'A messy, hopeful dreamer figuring out her life one stumble at a time.',
    tags: ['free', 'whimsical', 'dreamer', 'emotional', 'social', 'light'],
    vibe: ['Hopeful', 'Messy', 'Warm', 'Searching'],
    reel: ['Frances Ha', 'Lady Bird', 'The Worst Person in the World', '20th Century Women', 'Tiny Furniture', 'Mistress America'],
  },
  {
    id: 'mae-mona',
    name: 'Mona',
    actor: 'Sandrine Bonnaire',
    film: 'Vagabond',
    year: 1985,
    tier: 'deep',
    essence: 'Radical freedom with no safety net — a drifter who answers to no one.',
    tags: ['free', 'solitary', 'rebellious', 'outsider', 'survivor', 'principled'],
    vibe: ['Free', 'Untethered', 'Defiant', 'Raw'],
    reel: ['Vagabond', 'Into the Wild', 'Wendy and Lucy', 'Nomadland', 'Wild', 'Leave No Trace'],
  },

  // ── Leaders / principled hearts ────────────────────────────────────────────
  {
    id: 'atticus-finch',
    name: 'Atticus Finch',
    actor: 'Gregory Peck',
    film: 'To Kill a Mockingbird',
    year: 1962,
    tier: 'icon',
    essence: 'Quiet moral spine — doing what’s right when it costs him everything.',
    tags: ['principled', 'leader', 'controlled', 'tender', 'loyal', 'protector'],
    vibe: ['Principled', 'Calm', 'Steadfast', 'Decent'],
    reel: ['To Kill a Mockingbird', '12 Angry Men', 'A Man for All Seasons', 'Just Mercy', 'Spotlight', 'The Verdict'],
  },
  {
    id: 'maximus-aurelius-false',
    name: 'T’Challa',
    actor: 'Chadwick Boseman',
    film: 'Black Panther',
    year: 2018,
    tier: 'icon',
    essence: 'A leader balancing duty, grief, and the weight of doing right by everyone.',
    tags: ['leader', 'principled', 'dutiful', 'protector', 'controlled', 'loyal'],
    vibe: ['Noble', 'Composed', 'Dutiful', 'Strong'],
    reel: ['Black Panther', 'Black Panther: Wakanda Forever', 'Creed', 'Gladiator', 'The Woman King', 'Kingdom of Heaven'],
  },
  {
    id: 'celie',
    name: 'Celie',
    actor: 'Whoopi Goldberg',
    film: 'The Color Purple',
    year: 1985,
    tier: 'deep',
    essence: 'A wounded soul who slowly, fiercely reclaims her own life and voice.',
    tags: ['survivor', 'tender', 'wounded', 'seeker', 'principled', 'emotional'],
    vibe: ['Resilient', 'Tender', 'Awakening', 'Strong'],
    reel: ['The Color Purple', 'Mudbound', 'Beloved', 'Harriet', 'Just Mercy', 'If Beale Street Could Talk'],
  },
]
